# Generated by Django 4.2.30 on 2026-06-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_name', models.CharField(max_length=255, verbose_name='Corporate Debtor name')),
                ('bank_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=50)),
                ('is_cd_account', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounts.engagement')),
            ],
            options={
                'unique_together': {('bank_name', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(upload_to='uploads/')),
                ('original_filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('csv', 'CSV / Excel'), ('pdf_text', 'PDF (text)'), ('pdf_scan', 'PDF (scanned/OCR)'), ('image', 'Image (OCR)'), ('rpt', 'RPT (text report)'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('rows_extracted', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='statements.account')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txn_date', models.DateField(blank=True, null=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('txn_time', models.TimeField(blank=True, null=True)),
                ('narration_raw', models.TextField(blank=True)),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('balance_type', models.CharField(blank=True, max_length=2)),
                ('reference', models.CharField(blank=True, max_length=200)),
                ('txn_mode', models.CharField(blank=True, max_length=20)),
                ('counterparty_name', models.CharField(blank=True, max_length=255)),
                ('source_row', models.IntegerField(blank=True, null=True)),
                ('quality_flag', models.CharField(blank=True, max_length=100)),
                ('bank_json_data', models.JSONField(blank=True, null=True)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='statements.statement')),
            ],
        ),
    ]
