# Generated by Django 4.2.30 on 2026-06-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statements', '0002_statement_extraction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='statement',
            name='extraction_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
