# Generated by Django 4.2.30 on 2026-06-25 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statements', '0004_statement_cancel_requested_statement_celery_task_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statement',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='statement',
            name='correction_log',
            field=models.JSONField(blank=True, default=list, help_text='Log of manual corrections made by analyst'),
        ),
        migrations.AddField(
            model_name='statement',
            name='extraction_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='last_cleaned_export_at',
            field=models.DateTimeField(blank=True, help_text='When cleaned data was last exported', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='last_cleaned_export_by',
            field=models.ForeignKey(blank=True, help_text='User who exported cleaned data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_completed_at',
            field=models.DateTimeField(blank=True, help_text='When validation checks completed', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_critical_count',
            field=models.IntegerField(default=0, help_text='Count of CRITICAL severity issues'),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_high_count',
            field=models.IntegerField(default=0, help_text='Count of HIGH severity issues'),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_issues',
            field=models.JSONField(blank=True, default=list, help_text='List of validation issues detected (JSON)'),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_issues_count',
            field=models.IntegerField(default=0, help_text='Total number of validation issues found'),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_notes',
            field=models.TextField(blank=True, help_text='Analyst notes on validation issues and corrections'),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_rating',
            field=models.CharField(blank=True, choices=[('CLEAN', 'Clean'), ('ACCEPTABLE', 'Acceptable'), ('QUALIFIED', 'Qualified'), ('UNRELIABLE', 'Unreliable')], help_text='Data quality rating (CLEAN, ACCEPTABLE, QUALIFIED, UNRELIABLE)', max_length=20),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_reviewed_at',
            field=models.DateTimeField(blank=True, help_text='When analyst completed validation review', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_reviewed_by',
            field=models.ForeignKey(blank=True, help_text='User who reviewed/approved validation issues', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_statements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_started_at',
            field=models.DateTimeField(blank=True, help_text='When validation checks started', null=True),
        ),
        migrations.AddField(
            model_name='statement',
            name='validation_status',
            field=models.CharField(choices=[('NOT_RUN', 'Not Run'), ('PENDING_REVIEW', 'Pending Review'), ('CLEAN', 'Clean'), ('ACCEPTABLE', 'Acceptable'), ('QUALIFIED', 'Qualified'), ('UNRELIABLE', 'Unreliable')], default='NOT_RUN', help_text='Current state of validation workflow', max_length=20),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['account', '-uploaded_at'], name='statements__account_1ed405_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['extraction_status'], name='statements__extract_59a58a_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['validation_status'], name='statements__validat_46c083_idx'),
        ),
        migrations.AddIndex(
            model_name='statement',
            index=models.Index(fields=['validation_rating'], name='statements__validat_371887_idx'),
        ),
    ]
