# Generated by Django 4.2.30 on 2026-06-25 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('statements', '0005_alter_statement_options_statement_correction_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_identified_by',
            field=models.CharField(blank=True, choices=[('RULE_BASED', 'Rule-Based'), ('OLLAMA', 'Ollama LLM'), ('ANALYST', 'Analyst'), ('UNIDENTIFIED', 'Unidentified')], max_length=20),
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('beneficiary_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDIVIDUAL', 'Individual'), ('BANK', 'Bank'), ('GOVERNMENT', 'Government'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('identification_method', models.CharField(choices=[('RULE_BASED', 'Rule-Based'), ('OLLAMA', 'Ollama LLM'), ('ANALYST', 'Analyst')], max_length=20)),
                ('highest_confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('identification_count', models.IntegerField(default=1)),
                ('total_debit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_credit', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_position', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('transaction_count', models.IntegerField(default=0)),
                ('first_transaction_date', models.DateField(blank=True, null=True)),
                ('last_transaction_date', models.DateField(blank=True, null=True)),
                ('account_numbers', models.JSONField(blank=True, default=list)),
                ('ifsc_codes', models.JSONField(blank=True, default=list)),
                ('above_aggregate_threshold', models.BooleanField(default=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counterparties', to='statements.statement')),
            ],
            options={
                'ordering': ['-total_debit', '-total_credit'],
                'unique_together': {('statement', 'name')},
            },
        ),
        migrations.CreateModel(
            name='BeneficiaryIdentification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_identified', models.CharField(choices=[('LAYER_1', 'Rule-Based'), ('LAYER_2', 'Ollama LLM'), ('LAYER_3', 'Analyst')], max_length=20)),
                ('confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('extraction_basis', models.TextField()),
                ('layer1_result', models.JSONField(blank=True, null=True)),
                ('layer2_result', models.JSONField(blank=True, null=True)),
                ('analyst_confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst_confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_identifications', to=settings.AUTH_USER_MODEL)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statements.counterparty')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiary_identifications', to='statements.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='statements.counterparty'),
        ),
    ]
